### ISSUE TITLE
Python Exception when trying to start tvchopo

### ISSUE THREAD

**Issue by JaviMuller** [elchocolate/repotvchopo#1]
Hi, I am stumbling into an issue when trying to start tvchopo. I am running kodi 19.1. I have looked into the logs to see more info, and the issue seems to be this one:

```
2021-06-23 16:33:08.736 T:15284   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'LOGNOTICE' from 'xbmc' (unknown location)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.tvchopo\default.py", line 1, in <module>
                                                       exec("".join(map(chr,[int("".join(str({':(': 4,
                                                     File "<string>", line 32, in <module>
                                                     File "<string>", line 18, in <module>
                                                     File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 35, in <module>
                                                       from resolveurl import common
                                                     File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\common.py", line 20, in <module>
                                                       from resolveurl.lib import log_utils
                                                     File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\log_utils.py", line 22, in <module>
                                                       from xbmc import LOGDEBUG, LOGERROR, LOGNOTICE, LOGWARNING
                                                   ImportError: cannot import name 'LOGNOTICE' from 'xbmc' (unknown location)
                                                   -->End of Python script error report<--
```

**Comment by JaviMuller** [comment]
Solution seems to be in here: https://forum.kodi.tv/showthread.php?tid=336747&page=12
Changing from LOGNOTICE to LOGINFO, since LOGNOTICE was deprecated in kodi 19

**Comment by JaviMuller** [comment]
I have managed to solve it by changing the file in Appdata of resolveurl
